title: Hiago Hubert Blog
description: Blog de desenvolvimento de software e segurança da informação

url: https://hiagohubert.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate, jekyll-seo-tag]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Contato
   url: /contact

social:
   github: hiagohubert
   twitter: HubertHiago
   facebook: hiago.hubert
   email: hiagohubert@protonmail.com

google_analytics: "UA-92163450-1"
