title: Hiago Hubert Blog
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://hiagohubert.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Contato
   url: /contact

social:
   github: hiagohubert
   twitter: HubertHiago
   facebook: hiago.hubert
   email: hiagohubert@protonmail.com

google_analytics: "UA-58263416-1"
